# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import fromleaf_playing.darly.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DarlyPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to=fromleaf_playing.darly.models.get_upload_to)),
                ('comment', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
