# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fromleaf_playing.ourhockey.models.Member


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField()),
                ('attended_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_day', models.DateField()),
                ('game_type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=0)),
                ('status', models.CharField(default='00', max_length=2)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=fromleaf_playing.ourhockey.models.Member.Member.get_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(default='test')),
                ('text', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ourhockey.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('back_number', models.IntegerField(default=0, unique=True)),
                ('position', models.CharField(max_length=100)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ourhockey.Member')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ourhockey.Member'),
        ),
    ]
