# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fromleaf_playing.ourhockey.models.Player


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=0)),
                ('status', models.CharField(default='00', max_length=2)),
                ('profile_image', models.ImageField(null=True, upload_to=fromleaf_playing.ourhockey.models.Player.Member.get_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back_number', models.IntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourhockey.Player'),
        ),
        migrations.AddField(
            model_name='member',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ourhockey.Player'),
        ),
    ]
