# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fromleaf_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fromleaf_common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page_container', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fromleaf_common.PageContainer')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('language', models.CharField(blank=True, max_length=200)),
                ('system', models.CharField(blank=True, max_length=200)),
                ('framework', models.CharField(blank=True, max_length=200)),
                ('architecture', models.ImageField(blank=True, upload_to=fromleaf_history.models.Project.get_upload_to)),
                ('architecture_describe', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fromleaf_history.Company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='history_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fromleaf_history.HistoryPage'),
        ),
    ]
