# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fromleaf_common.models.user


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fromleaf_aboutme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.PositiveIntegerField()),
                ('cellphone_number', models.PositiveIntegerField()),
                ('profile_image', models.ImageField(upload_to=fromleaf_common.models.user.ExtraUserInfo.get_upload_to)),
                ('blog_address', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('grade', models.CharField(choices=[('GUEST', 'Guest'), ('MEMBER', 'Member'), ('OWNER', 'Owner'), ('ADMIN', 'Administrator')], default='MEMBER', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PageContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='page_container', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField(help_text='Input Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aboutme_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fromleaf_aboutme.AboutMePage')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField(default='1980-01-01')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSNSInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.CharField(max_length=200)),
                ('github_address', models.URLField()),
                ('facebook_id', models.CharField(max_length=200)),
                ('facebook_address', models.URLField()),
                ('linkedin_id', models.CharField(max_length=200)),
                ('linkedin_address', models.URLField()),
                ('extra_user_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fromleaf_common.ExtraUserInfo')),
            ],
        ),
    ]
